config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_hooks:
    src: config/hooks
    dst: ~/.config/hooks
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_packages:
    src: config/packages
    dst: ~/.config/packages
  d_qutebrowser:
    src: config/qutebrowser
    dst: ~/.config/qutebrowser
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_wofi:
    src: config/wofi
    dst: ~/.config/wofi
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_waybar:
    src: config/waybar
    dst: ~/.config/waybar
  f_autostart.conf:
    src: config/hypr/Autostart.conf
    dst: ~/.config/hypr/Autostart.conf
  f_envs.conf:
    src: config/hypr/Envs.conf
    dst: ~/.config/hypr/Envs.conf
  f_hypridle.conf:
    src: config/hypr/hypridle.conf
    dst: ~/.config/hypr/hypridle.conf
  f_hyprland.conf:
    src: config/hypr/hyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_hyprlock.conf:
    src: config/hypr/hyprlock.conf
    dst: ~/.config/hypr/hyprlock.conf
  f_keybindings.conf:
    src: config/hypr/Keybindings.conf
    dst: ~/.config/hypr/Keybindings.conf
  f_laptopenvs.conf:
    src: config/hypr/laptopEnvs.conf
    dst: ~/.config/hypr/laptopEnvs.conf
  f_laptopmonitor.conf:
    src: config/hypr/laptopMonitor.conf
    dst: ~/.config/hypr/laptopMonitor.conf
  f_laptopvariables.conf:
    src: config/hypr/laptopVariables.conf
    dst: ~/.config/hypr/laptopVariables.conf
  f_monitors.conf:
    src: config/hypr/Monitors.conf
    dst: ~/.config/hypr/Monitors.conf
  f_pyprland.toml:
    src: config/hypr/pyprland.toml
    dst: ~/.config/hypr/pyprland.toml
  f_variables.conf:
    src: config/hypr/Variables.conf
    dst: ~/.config/hypr/Variables.conf
  d_doom:
    src: config/doom
    dst: ~/.config/doom
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  f_laptophyprland.conf:
    src: config/hypr/laptopHyprland.conf
    dst: ~/.config/hypr/hyprland.conf
  f_laptopconfig:
    src: config/waybar/laptopConfig
    dst: ~/.config/waybar/config
  d_scripts:
    src: config/scripts
    dst: ~/.config/scripts
  f_waybar_laptopconfig:
    src: config/waybar/laptopConfig
    dst: ~/.config/waybar/laptopConfig
  d_waybar_scripts:
    src: config/waybar/scripts
    dst: ~/.config/waybar/scripts
  d_themes:
    src: config/waybar/Themes
    dst: ~/.config/waybar/Themes
  f_colors.css:
    src: config/waybar/colors.css
    dst: ~/.config/waybar/colors.css
  f_mediaplayer.py:
    src: config/waybar/mediaplayer.py
    dst: ~/.config/waybar/mediaplayer.py
  f_style.css:
    src: config/waybar/style.css
    dst: ~/.config/waybar/style.css
  f_clean_cache.hook:
    src: config/hooks/clean_cache.hook
    dst: ~/.config/hooks/clean_cache.hook
  f_maintainpackages.hook:
    src: config/hooks/maintainPackages.hook
    dst: ~/.config/hooks/maintainPackages.hook
  d_service:
    src: config/service
    dst: ~/.config/service
  d_rsnapshot:
    src: config/rsnapshot
    dst: ~/.config/rsnapshot
  d_config_tmux:
    src: config/tmux
    dst: ~/.config/tmux
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
profiles:
  Lok:
    dotfiles:
    - d_alacritty
    - d_dunst
    - d_hooks
    - d_i3
    - d_kitty
    - d_nvim
    - d_packages
    - d_qutebrowser
    - d_rofi
    - d_wofi
    - d_sway
    - d_waybar
    - f_autostart.conf
    - f_envs.conf
    - f_hypridle.conf
    - f_hyprland.conf
    - f_hyprlock.conf
    - f_keybindings.conf
    - f_laptopenvs.conf
    - f_laptopmonitor.conf
    - f_laptopvariables.conf
    - f_monitors.conf
    - f_pyprland.toml
    - f_variables.conf
    - d_doom
    - f_starship.toml
    - d_scripts
    - f_clean_cache.hook
    - f_maintainpackages.hook
    - d_service
    - d_rsnapshot
    - d_config_tmux
    - d_zsh
  zeus:
    dotfiles:
    - d_alacritty
    - d_dunst
    - d_hooks
    - d_i3
    - d_kitty
    - d_nvim
    - d_packages
    - d_qutebrowser
    - d_rofi
    - d_wofi
    - d_sway
    - f_autostart.conf
    - f_envs.conf
    - f_hypridle.conf
    - f_hyprlock.conf
    - f_keybindings.conf
    - f_laptopenvs.conf
    - f_laptopmonitor.conf
    - f_laptopvariables.conf
    - f_monitors.conf
    - f_pyprland.toml
    - f_variables.conf
    - d_doom
    - f_starship.toml
    - f_laptophyprland.conf
    - f_laptopconfig
    - d_scripts
    - f_waybar_laptopconfig
    - d_waybar_scripts
    - d_themes
    - f_colors.css
    - f_mediaplayer.py
    - f_style.css
