#+TITLE: starship Config
#+AUTHOR: MDB Dev
#+DESCRIPTION: Starship Config
#+auto_tangle: t
#+STARTUP: showeverything

* TOC: :TOC:
:PROPERTIES:
:ID:       0e175da5-433d-4539-bcfe-59255aa13a22
:END:
- [[#literate-config][Literate Config:]]
- [[#possible-options-for-what-to-display-in-the-prompt][Possible options for what to display in the prompt:]]
- [[#general-settings][General Settings:]]
  - [[#set-timeout][Set Timeout:]]
  - [[#print-new-line-at-start-of-the-prompt][Print New Line at Start of the Prompt:]]
  - [[#enable-the-package-module][Enable the Package Module:]]
  - [[#show-cmd-duration][Show CMD Duration:]]
  - [[#set-error-symbol][Set Error Symbol:]]
  - [[#set-env][Set Env:]]
  - [[#set-shell-symbol][Set Shell Symbol:]]
- [[#modules][Modules:]]
  - [[#general-modules][General Modules:]]
  - [[#laptop-modules][Laptop Modules:]]
- [[#desktop-configuration][Desktop Configuration:]]
- [[#laptop-configuration][Laptop Configuration:]]

* Literate Config:
:PROPERTIES:
:ID:       cbe8e8ba-b883-4094-a012-dbac2ceedac0
:END:
- This is my personal starship config it is structured as a literate configuration.
- Inspired by the methodology presented at [[https://leanpub.com/lit-config/read][Literate Configuration]].
- This approach blends detailed documentation directly with the code, offering clear insights into the purpose and functionality of each configuration snippet, making it both user-friendly and easy to maintain.
- Great video by DT Tube here on how to write literate configs:
  - https://www.youtube.com/watch?v=eF4cJlBNtdQ&themeRefresh=1

* Possible options for what to display in the prompt:
:PROPERTIES:
:ID:       9f67e361-67d5-4595-8b1c-dd87b80a52d8
:END:
- Just here for reference, as I want to know what I can add at a later date if need be.
#+begin_src toml
#prompt_order = [ "username", "hostname", "kubernetes", "directory", "git_branch", "git_commit", "git_state", "git_status", "hg_branch", "docker_context", "package", "dotnet", "elixir", "elm", "erlang", "golang", "java", "julia", "nim", "nodejs", "ocaml", "php", "purescript", "python", "ruby", "rust", "terraform", "zig", "nix_shell", "conda", "memory_usage", "aws", "env_var", "crystal", "cmd_duration", "custom", "line_break", "jobs", "battery", "time", "character", ]
#+end_src

* General Settings:
:PROPERTIES:
:ID:       76f3d5d3-24fd-4c1a-b2db-a622987c8407
:END:
** Set Timeout:
:PROPERTIES:
:ID:       1bd1b996-57b3-402a-a496-8fa6c29d7b8b
:END:
#+NAME:Set-Timeout
Useful for large git dirs.
#+begin_src toml
command_timeout = 10000

#+end_src

** Print New Line at Start of the Prompt:
:PROPERTIES:
:ID:       6876c7ad-02c8-40f3-8143-2422aaa4993b
:END:
#+NAME:Print-NewLine
- Don't print a new line at the start of the prompt
#+begin_src toml
add_newline = true

#+end_src

** Enable the Package Module:
:PROPERTIES:
:ID:       24ba01b8-adc1-4b12-a96f-583ed97d12bc
:END:
#+NAME:Enable-Package
- Disable the package module, hiding it from the prompt completely
#+begin_src toml
[package]
disabled = false

#+end_src

** Show CMD Duration:
:PROPERTIES:
:ID:       ab3f3433-64db-4c5e-af0a-1b6e8275f608
:END:
#+NAME:Show-CMD
- Show command duration over 10,000 milliseconds (=10 sec)
#+begin_src toml
[cmd_duration]
min_time = 10_000
format = " took [$duration]($style)"

#+end_src
** Set Error Symbol:
:PROPERTIES:
:ID:       4cb288d7-e9eb-492a-8f14-3e01617e05b0
:END:
#+NAME:Set-Error
- This is the last character you see before the stuff you type
#+begin_src toml
[character]
error_symbol = "[✖](bold red) "

#+end_src

** Set Env:
:PROPERTIES:
:ID:       cc4fcff1-4e4c-4788-a0a6-fa364cb28467
:END:
#+NAME:Set-Env
#+begin_src conf
[env_var.SHELL]
variable = "SHELL"
default = "unknown shell"
style = "bold dimmed white #44475A"

#+end_src

** Set Shell Symbol:
:PROPERTIES:
:ID:       795f321b-f3db-4feb-9bef-89c01fcbb167
:END:
#+NAME:Set-Shell
#+begin_src toml
[shell]
fish_indicator = ""
bash_indicator = "BSH"
powershell_indicator = "__"
unknown_indicator = "mystery shell"
style = "bold dimmed blue"
disabled = false

#+end_src

* Modules:
:PROPERTIES:
:ID:       9776f96e-62c7-4787-9aa7-c5d90c440978
:END:
** General Modules:
:PROPERTIES:
:ID:       4e694f2b-7bf4-435b-a8bf-86ed4bef827b
:END:
*** Memory Usage Module:
:PROPERTIES:
:ID:       f3807696-121b-456a-b8f3-741de802d10e
:END:
#+NAME:Mem-Module
#+begin_src toml
[memory_usage]
disabled = false
threshold = -1
symbol = " "
#style = "bold #50FA7B"
format = "$symbol[${ram}( | ${swap})]($style) "

#+end_src
*** Time Module:
:PROPERTIES:
:ID:       7815ad0b-ced2-45a2-b1a5-de89eddb5b28
:END:
#+NAME:Time-Module
#+begin_src toml
[time]
time_format = "%T"
format = "🕙 $time($style) "
#style = "#F8F8F2"
disabled = false

#+end_src
*** Username Module:
:PROPERTIES:
:ID:       220a4925-a4ff-44dc-82bb-3c21c57baa2d
:END:
#+NAME:User-Module
#+begin_src toml
[username]
#style_user = "#BD93F9"
show_always = true

#+end_src

*** Hostname Module:
:PROPERTIES:
:ID:       f46b2bc6-7177-455f-9f7e-715487a4a7d9
:END:
#+NAME:Host-Module
#+begin_src conf
[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

#+end_src
*** Directory Module:
:PROPERTIES:
:ID:       4ca585f4-edc7-47e6-bd3a-f644259f3e1f
:END:
#+NAME:Dir-Module
#+begin_src conf
[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "
#style = "bold underline #8BE9FD"

#+end_src

*** Git Module:
:PROPERTIES:
:ID:       2b8c7726-314d-4ffe-a07f-9353810e7662
:END:

#+NAME:Git-Module
#+begin_src toml
[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "🍣 "
style = "bold #F1FA8C"

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 ×${count}"
behind = "🐢 ×${count}"
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count}"
untracked = "🛤️  ×${count}"
stashed = "📦 "
modified = "📝 ×${count}"
staged = "🗃️  ×${count}"
renamed = "📛 ×${count}"
deleted = "🗑️  ×${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

#+end_src

*** Vargrant Module:
:PROPERTIES:
:ID:       4ad870a2-eeac-42ee-ac00-f7df16aa9796
:END:
#+NAME:VG-Module
#+begin_src toml
[vagrant]
format = "via [⍱ $version](bold white) "

#+end_src

*** Docker Module:
:PROPERTIES:
:ID:       e44d36e2-d13f-432a-9cc0-a42b908ef292
:END:
#+NAME:Docker-Module
#+begin_src toml
[docker_context]
format = "via [🐋 $context](blue bold)"

#+end_src
*** Kubernetes Module:
:PROPERTIES:
:ID:       5b061baf-1903-43b3-b607-c2e414461fc6
:END:

#+NAME:Kube-Module
#+begin_src toml
[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
".*/openshift-cluster/.*" = "openshift"
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

#+end_src
*** Python Module:
:PROPERTIES:
:ID:       e2a1da87-e4a1-4e57-b193-91f5a2addc16
:END:
#+NAME:Py-Module
#+begin_src toml
[python]
format = "[$symbol$version]($style) "
style = "bold green"

#+end_src

*** Rust Module:
:PROPERTIES:
:ID:       364a5c8f-b3dc-47ef-a709-5ff52c2105ad
:END:
#+NAME:Rust-Module
#+begin_src toml
[rust]
format = "[$symbol$version]($style) "
style = "bold green"

#+end_src

*** PHP Module:
:PROPERTIES:
:ID:       73c254b7-f8ad-41f1-ac53-cf8670dc900a
:END:
#+NAME:PHP-Module
#+begin_src toml
[php]
format = "via [🔹 $version](147 bold) "

#+end_src

** Laptop Modules:
:PROPERTIES:
:ID:       66009dab-dbbb-4e12-9fe6-5ce2132ddf5e
:END:
*** Battery Module:
:PROPERTIES:
:ID:       bacfc446-2b2f-43dc-b7bb-6895587e22f0
:END:
#+NAME:Bat-Module
#+begin_src toml
[battery]
full_symbol = '🔋 '
charging_symbol = '⚡ '
discharging_symbol = '💀 '

#+end_src
* Desktop Configuration:
:PROPERTIES:
:ID:       5467004f-7609-4ab2-b87c-05048909312e
:header-args: :tangle ~/.config/starship/starship.toml
:END:

- Generate starship.toml
#+begin_src conf :noweb yes
<<Set-Timeout>>
<<Print-NewLine>>
<<Enable-Package>>
<<Show-CMD>>
<<Set-Error>>
<<Set-Env>>
<<Set-Shell>>
<<Mem-Module>>
<<Time-Module>>
<<User-Module>>
<<Host-Module>>
<<Dir-Module>>
<<Git-Module>>
<<VG-Module>>
<<Docker-Module>>
<<Kube-Module>>
<<Py-Module>>
<<Rust-Module>>
<<PHP-Module>>
#+end_src
* Laptop Configuration:
:PROPERTIES:
:ID:       255529a0-036a-4d06-b038-be346fdb45d7
:header-args: :tangle ~/.config/starship/laptopStarship.toml
:END:
- Generate laptopStarship.toml
#+begin_src conf :noweb yes
<<Set-Timeout>>
<<Print-NewLine>>
<<Enable-Package>>
<<Show-CMD>>
<<Set-Error>>
<<Set-Env>>
<<Set-Shell>>
<<Mem-Module>>
<<Time-Module>>
<<User-Module>>
<<Host-Module>>
<<Dir-Module>>
<<Git-Module>>
<<VG-Module>>
<<Docker-Module>>
<<Kube-Module>>
<<Py-Module>>
<<Rust-Module>>
<<PHP-Module>>
<<Bat-Module>>
#+end_src
