#+TITLE: Waybar Config
#+AUTHOR: MDB Dev
#+DESCRIPTION: Personal waybar Config
#+auto_tangle: t
#+STARTUP: showeverything
* TOC: :TOC:
:PROPERTIES:
:ID:       fc50f8cb-fb96-4c14-8cd2-c6e4f9059c25
:END:
- [[#literate-config][Literate Config:]]
- [[#desktop-configuration][Desktop Configuration:]]
- [[#laptop-configuration][Laptop Configuration:]]
  - [[#laptop-battery-module-configuration][Laptop-Battery-Module-Configuration:]]

* Literate Config:
:PROPERTIES:
:ID:       6f08e094-c0f0-4871-9faa-2e49c6f6d359
:END:
- This is my personal Waybar config it is structured as a literate configuration.
- Inspired by the methodology presented at [[https://leanpub.com/lit-config/read][Literate Configuration]].
- This approach blends detailed documentation directly with the code, offering clear insights into the purpose and functionality of each configuration snippet, making it both user-friendly and easy to maintain.
- Great video by DT Tube here on how to write literate configs:
  - https://www.youtube.com/watch?v=eF4cJlBNtdQ&themeRefresh=1
* Desktop Configuration:
:PROPERTIES:
:ID:       0fc9e585-b145-4577-8d54-d126fb1d5278
:END:
:PROPERTIES:
:ID:       e820e8f3-817f-4414-9b8a-e1b3c6275ec0
#+PROPERTY: header-args :tangle /home/martin/.config/waybar/config
:END:
#+begin_src conf
{
  "layer": "top", "position": "top",
  "modules-left": ["custom/logo", "clock",  "custom/weather", "disk", "memory", "cpu", "temperature", "custom/powerDraw", "hyprland/window" ],
  "modules-center": [  "hyprland/workspaces" , "idle_inhibitor" ],
  "modules-right": ["tray",  "custom/clipboard", "backlight", "bluetooth", "wireplumber", "network",  "battery" ],
  "reload_style_on_change":true,

  "custom/logo": {
    "format": "󱄅",
    "tooltip": false
  },

  "hyprland/workspaces": {
	"format": "{icon}",
	"format-icons": {
		"1": "",
		"2": "",
		"3": "",
		"4": "",
		"5": "",
		"6": "",
		"active": "",
		"default": ""
	},
       "persistent-workspaces": {
         "*": [ 2, 3, 4, 5, 6 ]
       }
},

"idle_inhibitor":{
  "format": "<span font='16'>{icon} </span>",
  "format-icons": {
    "activated":"󰈈",
    "deactivated":"󰈉"
  }
},

"custom/weather": {
  "format": "{}",
  "return-type": "json",
  "exec": "~/.config/waybar/scripts/weather.sh",
  "interval": 10,
  "on-click": "brave https://wttr.in"
},


"clock": {
      "format": "{:%I:%M:%S %p}",
      "interval":1,
      "tooltip-format": "\n<big>{:%Y %B}</big>\n<tt><small>{calendar}</small></tt>",
      "calendar-weeks-pos": "right",
      "today-format": "<span color='#7645AD'><b><u>{}</u></b></span>",
      "format-calendar": "<span color='#aeaeae'><b>{}</b></span>",
      "format-calendar-weeks": "<span color='#aeaeae'><b>W{:%V}</b></span>",
      "format-calendar-weekdays": "<span color='#aeaeae'><b>{}</b></span>"
      },

  "bluetooth": {
  "format-on": "",
  "format-off": "",
  "format-disabled": "󰂲",
  "format-connected": "󰂴",
  "format-connected-battery": "{device_battery_percentage}% 󰂴",
  "tooltip-format": "{controller_alias}\t{controller_address}\n\n{num_connections} connected",
  "tooltip-format-connected": "{controller_alias}\t{controller_address}\n\n{num_connections} connected\n\n{device_enumerate}",
  "tooltip-format-enumerate-connected": "{device_alias}\t{device_address}",
  "tooltip-format-enumerate-connected-battery": "{device_alias}\t{device_address}\t{device_battery_percentage}%",
  "on-click": "blueman-manager"
 },

"network": {
      "format-wifi": " ",
      "format-ethernet":" ",
      "format-disconnected": "",
      "tooltip-format": "{ipaddr}",
      "tooltip-format-wifi": "{essid} ({signalStrength}%)  | {ipaddr}",
      "tooltip-format-ethernet": "{ifname} 🖧 | {ipaddr}",
      "on-click": "nm-connection-editor"
    },

"battery": {
    "interval":1,
        "states": {
            "good": 95,
            "warning": 30,
            "critical": 20
        },
        "format": "{capacity}%  {icon} ",
        "format-charging": "{capacity}% 󰂄 ",
        "format-plugged": "{capacity}% 󰂄 ",
        "format-alt": "{time} {icon}",
            "format-icons": [
          "󰁻",
          "󰁼",
          "󰁾",
          "󰂀",
          "󰂂",
          "󰁹"
        ]
    },
"backlight": {
  "device": "intel_backlight",
  "format": "<span font='12'>{icon}</span>",
  "format-icons": [
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
  ],
  "on-scroll-down": "brightnessctl set +5%",
  "on-scroll-up": "brightnessctl set 5%-",
  "smooth-scrolling-threshold": 1
},

 "disk": {
    "interval": 30,
    "format": "  {percentage_used}%",
    "path": "/"
  },


  "cpu": {
      "interval": 1,
      "format": " {usage}%",
      "min-length": 6,
      "max-length": 6,
      "on-click": "alacritty -e 'btop'",
      "format-icons": ["▁", "▂", "▃", "▄", "▅", "▆", "▇", "█"]
 },

"memory": {
  "format": " {percentage}%",
  "on-click": "alacritty -e 'btop'"
},

 "hyprland/window": {
    "format": "( {class} )",
    "rewrite": {
         "(.*) - Mozilla Firefox": "🌎 $1",
         "(.*) - zsh": "> [$1]"
    }
},

"temperature": {
  "format": " {temperatureC}°C",
  "format-critical": " {temperatureC}°C",
  "interval": 1,
  "critical-threshold": 80,
  "on-click": "btop"
 },

"wireplumber": {
  "format": "{volume}% {icon}",
  "format-bluetooth": "󰂰",
  "format-muted": "<span font='12'></span>",
  "format-icons": {
    "headphones": "",
    "bluetooth": "󰥰",
    "handsfree": "",
    "headset": "󱡬",
    "phone": "",
    "portable": "",
    "car": "",
    "default": ["󰕿", "󰖀", "󰕾"]
  },
  "scroll-step": 5,
  "on-click": "jamesdsp",
  "on-click-right": "pavucontrol",
  "tooltip-format": "{icon} {volume}%"
},


"tray": {
    "icon-size": 14,
    "spacing": 10
},

"upower": {
    "show-icon": false,
    "hide-if-empty": true,
    "tooltip": true,
    "tooltip-spacing": 20
},

  "custom/powerDraw": {
    "format": "{}",
    "interval": 1,
    "exec": "~/.config/waybar/scripts/powerdraw.sh",
    "return-type": "json"
  }

}
#+end_src
* Laptop Configuration:
:PROPERTIES:
:ID:       f90eafbd-3099-4bbe-aeda-550f87c3bcf3
:header-args: :tangle /home/martin/.config/waybar/laptopConfig
:END:

- My laptop configuration is nearly identical to my desktop configuration bar a battery display.
  - Due to this being a literate config, I can reference all previous blocks whilst inserting the battery configuration I want. This enables me not to have nearly duplicate literate configs.
** Laptop-Battery-Module-Configuration:
:PROPERTIES:
:ID:       ab131eb2-e032-40e7-a845-bb9c87c0e7f3
:END:
#+NAME: Laptop-Battery-Module-Configuration
#+begin_src conf
    // Battery Module Configuration:
    "battery": {
           "states": {
                "warning": 30,
                "critical": 15
          },
          "format": "{icon} {capacity}%",
          "format-charging": " {capacity}%",
          "format-plugged": " {capacity}%",
          "format-alt": "{time} {icon}",
          "format-full": " {capacity}%",
          "format-icons": ["", "", ""]
    },
    "custom/PBPbattery": {
        "exec": "~/.config/waybar/scripts/PBPbattery.sh",
        "format": "{}",
    },
#+end_src

#+begin_src conf :noweb yes
<<Opening-Bracket>>
<<Waybar-Layer>>
<<Waybar-Position>>
<<Waybar-Height>>
<<Modules-Left>>
<<Modules-Center>>
<<Modules-Right>>
<<Workspace-Configuration>>
<<Hyprland-Module-Configuration>>
<<Tray-Module-Configuration>>
<<Clock-Module-Configuration>>
<<CPU-Module-Configuration>>
<<CPU-Temprature-Module-Configuration>>
<<RAM-Module-Configuration>>
<<Network-Module-Configuration>>
<<Audio-Module-Configuration>>
<<Laptop-Battery-Module-Configuration>>
<<Disk-Settings-Module-Configuration>>
<<Closing-Bracket>>
#+end_src
