(package! emojify)
(package! org-super-agenda)
(package! magithub)
(package! flycheck-aspell)
(package! calfw)
(package! calfw-org)
(package! dashboard)
(package! dired-open)
(package! dired-subtree)
(package! dirvish)
(package! dmenu)
(package! elfeed-goodies)
(package! evil-tutor)
(package! exwm)
(package! ivy-posframe)
(package! mw-thesaurus)
(package! org-auto-tangle)
(package! org-web-tools)
(package! ox-hugo)
(package! peep-dired)
(package! rainbow-mode)
(package! resize-window)
(package! wc-mode)
(package! beacon)
(package! olivetti)
(package! powershell)
(package! org-download)
(package! org-ros)
(package! mini-frame)
(package! tron-legacy-theme)

(package! vlf :recipe (:host github :repo "emacs-straight/vlf" :files ("*.el"))
  :pin "9b7bc521e54af2c7a5c882e4758b66ee4af1a152")
;; For emacs-everywhere browser integration
(package! atomic-chrome)
(package! git-commit
  :recipe (:host github :repo "magit/magit" :files ("lisp/git-commit.el") :local-repo "magit2"))
