
[scrolling]
history = 100_000

[window]
dynamic_padding = false
opacity = 1
title = "Alacritty"

  [window.class]
  general = "Alacritty"
  instance = "Alacritty"

  [window.padding]
  x = 10
  y = 10

[font]
size = 13.5

  [font.bold]
  family = "JetBrains Mono"
  style = "Bold"

  [font.bold_italic]
  family = "Ubuntu Mono"
  style = "Mono Bold"

  [font.italic]
  family = "Ubuntu Mono"
  style = "Mono Bold"

  [font.normal]
  family = "JetBrains Mono"

  [font.offset]
  x = 0
  y = 1

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = [
  "~/.config/alacritty/themes/themes/doom_one.toml"
]
